version: '3'

services:
  redis:
    container_name: redis
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - ../redisdb/:/data
    restart: always
    env_file: ../.env

networks:
  default:
    external:
      name: redis